name: emergya
recipe: pantheon
config:
  site: emergya
  id: bc013568-31eb-4f22-8e21-2ad31a57ce3c
  xdebug: true
  config:
    php: .lando.php.ini
  webroot: web
  composer_version: "1.10.22"
services:
  appserver:
    overrides:
      environment:
        # Support debugging Drush with XDEBUG.
        PHP_IDE_CONFIG: "serverName=appserver"
        LANDO_HOST_IP: "host.docker.internal"
        XDEBUG_CONFIG: "remote_enable=1 remote_host=host.docker.internal"
  pma:
    type: phpmyadmin

tooling:
  npm:
    service: appserver
    cmd: cd /app/web/themes/hrs && npm
  npm2020:
    service: appserver
    cmd: cd /app/web/themes/hrs2020science && npm
  gulp:
    service: appserver
    cmd: cd /app/web/themes/hrs && gulp
  gulp2020:
    service: appserver
    cmd: cd /app/web/themes/hrs2020science && gulp
  gulpwatch2020:
    service: appserver
    cmd: cd /app/web/themes/hrs2020science && gulp watch
  behat:
    description: Run Behat tests.
    cmd:
      - appserver: /app/vendor/bin/behat --config=tests/behat/behat-lando.yml --strict --colors
