name: emergya
recipe: pantheon
config:
  site: emergya
  id: bc013568-31eb-4f22-8e21-2ad31a57ce3c
  xdebug: true
  config:
    php: .lando.php.ini
  webroot: web
  composer_version: 1.10.22
  framework: drupal8
services:
  appserver:
    overrides:
      environment:
        PHP_IDE_CONFIG: serverName=appserver
        LANDO_HOST_IP: host.docker.internal
        XDEBUG_CONFIG: remote_enable=1 remote_host=host.docker.internal
  pma:
    type: phpmyadmin
